# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 36586082f5b9c34ff6e266337ca02ec2e65c92c07ed79824a957bca01b8dfb2b16dc9a42c81ef87a7f5d026cd0986c05dc9121762c5560058d57593800b712cb

test:
  secret_key_base: 1009e03d815bd26def64b86b1d3f801b8afb4e37f77b1d48650c1879f052ef1b7ec57238b42df04f13e46401dd5587746997722dd9ad4c5af7df57e49372a430

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
